### ISSUE TITLE
Add default cache control headers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/cookiecutter-djangoapp#171]
We have begun using a CDN for more of our applications. To ensure that we get the intended behavior without requiring manual tuning of the CDN we should add cache control headers to our responses. This will ensure that we don't accidentally cache responses to API requests or other behaviors that should not be cached.

**Comment by noisecapella** [comment]
https://github.com/mitodl/bootcamp-ecommerce/pull/944
