### ISSUE TITLE
Add node.js support

### ISSUE THREAD

**Issue by noisecapella** [mitodl/cookiecutter-djangoapp#2]
I'm going to use this issue to keep track of the extra stuff I did to add support for things like browserify

**Comment by noisecapella** [comment]
Change command to

    command: >
      /bin/bash -c '
      export HOST_IP=$(netstat -nr | grep ^0\.0\.0\.0 | awk "{print \$2}") &&
      sleep 3 &&
      npm install --production --no-bin-links &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:$PORT'

**Comment by noisecapella** [comment]
Add package.json skeleton, for example

    {
      "name": "lore",
      "version": "0.0.0",
    }

**Comment by noisecapella** [comment]
Update apt.txt (this removes XML libraries but otherwise matches LORE):

    # Core requirements
    
    git
    libpq-dev
    python-pip
    python3-pip
    python-dev
    python3-dev
    npm
    nodejs
    
    
    # developer requirements
    postgresql-client
    
    # required for phantomjs
    libfreetype6
    libfontconfig1

**Comment by noisecapella** [comment]
Update Dockerfile:

    FROM ubuntu:trusty
    MAINTAINER ODL DevOps <mitx-devops@mit.edu>
    
    # Add package files
    WORKDIR /tmp
    
    # Install base packages
    COPY apt.txt /tmp/apt.txt
    RUN apt-get update &&\
        apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ") &&\
        ln -s /usr/bin/nodejs /usr/bin/node &&\
        pip install pip --upgrade
    
    # Add non-root user.
    RUN adduser --disabled-password --gecos "" mitodl
    
    # Install project packages
    
    # Python 2
    COPY requirements.txt /tmp/requirements.txt
    COPY test_requirements.txt /tmp/test_requirements.txt
    COPY doc_requirements.txt /tmp/doc_requirements.txt
    RUN pip install -r requirements.txt &&\
        pip install -r test_requirements.txt &&\
        pip install -r doc_requirements.txt
    
    # Python 3
    RUN pip3 install -r requirements.txt &&\
        pip3 install -r test_requirements.txt
    
    # Add project
    COPY . /src
    WORKDIR /src
    RUN chown -R mitodl:mitodl /src
    
    # Gather static
    RUN ./manage.py collectstatic --noinput
    RUN apt-get clean && apt-get purge
    USER mitodl
    
    # Set pip cache folder, as it is breaking pip when it is on a shared volume
    ENV XDG_CACHE_HOME /tmp/.cache
    
    # Set and expose port for uwsgi config
    EXPOSE 8070
    ENV PORT 8070
    CMD if [ -n "$WORKER" ]; then celery -A lore worker; else uwsgi uwsgi.ini; fi

**Comment by noisecapella** [comment]
Create static directory

**Comment by pwilkins** [comment]
@noisecapella @pdpinch Is it useful to add Sphinx documentation to the cookiecutter template?

**Comment by noisecapella** [comment]
I left it out since the server side would be minimal for the portal, but we should probably have it for the cookiecutter template.

**Comment by pwilkins** [comment]
Then I'll open a PR for doc on the cookie-cutter.
